15-django/productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls'))
]

15-django/productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'

urlpatterns = [
    path(
        '',
        views.index,
        name='productos'
    ),
    path(
        'formulario',
        views.formulario,
        name='formulario'
    ),
    path(
        '<int:producto_id>',
        views.detalle,
        name='detalle'
    )
]

15-django/productos/models.py
from django.db import models
from django.utils import timezone


class Categoria(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return str(self.nombre)


class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    # CASCADE: Elimina el producto
    # PROTECT: Lanza un error
    # RESTRICT: Solo elimina si no existen productos
    # SET_NULL: Actualiza a valor nulo
    # SET_DEFAULT: Asigna valor por defecto
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE
    )
    creado_en = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.nombre)

15-django/productos/forms.py
from . import models
from django.forms import ModelForm


class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'puntaje', 'categoria']

15-django/productly/views.py
from django.shortcuts import render


def index(request):
    return render(
        request,
        "index.html",
    )

15-django/productos/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ProductoForm
from .models import Producto


# def index(request):
# Retorna todos los elementos
# productos = Producto.objects.all()
# productos = Producto.objects.all().values()

# Filtra por puntaje igual a 3
# productos = Producto.objects.filter(puntaje=3)

# Filtra por puntaje mayor o igual a 3
# productos = Producto.objects.filter(puntaje__gte=3)

# Filtra por id igual a 1
# productos = Producto.objects.get(id=1)
# print(productos)
# return JsonResponse(list(productos), safe=False)

def index(request):
    productos = Producto.objects.all()

    return render(
        request,
        'productos.html',
        context={'productos': productos}
    )


def detalle(request, producto_id):
    # En caso de que se busque un elemento que no existe lanza 404
    # try:
    #     producto = Producto.objects.get(id=producto_id)

    #     return render(
    #         request,
    #         'detalle.html',
    #         context={'producto': producto}
    #     )
    # except Producto.DoesNotExist:
    #     raise Http404()

    producto = get_object_or_404(Producto, id=producto_id)

    return render(
        request,
        'detalle.html',
        context={'producto': producto}
    )


def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()

    return render(
        request,
        'producto_form.html',
        {'form': form}
    )

15-django/productos/templates/detalle.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h6>{{ producto.nombre }}</h6>
    <p>{{ producto.categoria }}</p>
    <p>{{ producto.stock }}</p>
    <p>{{ producto.puntaje }}</p>
    <p>{{ producto.creado_en }}</p>
</div>

{% endblock %}

15-django/productos/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Productos</h1>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Puntaje</th>
            <th>Categoría</th>
        </tr>
    </thead>

    <tbody>
        {%for producto in productos %}
        <tr>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.puntaje }}</td>
            <td>{{ producto.categoria }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

15-django/productos/templates/producto_form.html
{% extends 'base.html' %}

{% block content %}
  <form novalidate action="{% url 'productos:formulario' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar" />
  </form>
{% endblock %}

15-django/productos/templates/productos.html
{% extends 'base.html' %}

{% block content %}
<h1>Productos</h1>

<a href="{% url 'productos:formulario' %}">Nueo producto</a>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Puntaje</th>
            <th>Categoría</th>
            <th>Operaciones</th>
        </tr>
    </thead>

    <tbody>
        {%for producto in productos %}
        <tr>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.puntaje }}</td>
            <td>{{ producto.categoria }}</td>
            <td>
                <a href="{% url 'productos:detalle' producto.id %}">
                    Detalles
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

15-django/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'productos:productos' %}">Productos</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

15-django/templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

15-django/templates/django/forms/widgets/input.html
<input
    class="form-control {{ widget.attrs.class }}"
    type="{{ widget.type }}"
    name="{{ widget.name }}"
    {% if widget.value != None %}
        value="{{ widget.value|stringformat:'s' }}"
    {% endif %}
    {% include "django/forms/widgets/attrs.html" %}
>

15-django/templates/django/forms/widgets/select.html
<select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %} class="form-select">{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
</select>

15-django/templates/form_snippet.html
{% load add_attr %}

{% for field in form %}
  <div class="mb-3">
    {{ field.label_tag }}
    {% if field.errors %}
      {{ field | add_attr:'class:is-invalid' }}
    {% else %}
      {{ field }}
    {% endif %}
    <div class="invalid-feedback">
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
    </div>
  </div>
{% endfor %}

15-django/templates/index.html
{% extends 'base.html' %}

{% block content %}
    Hola mundo!
{% endblock %}